aa = {
'F':['UUC','UUU'],
'S':['UCU','UCC','UCA','UCG','AGU','AGC'],
'Y':['UAU','UAC'],
'Stop':['UAG','UGA','UAA'],
'C':['UGU','UGC'],
'W':['UGG'],
'L':['UUA','UUG','CUU','CUC','CUA','CUG'],
'P':['CCU','CCC','CCA','CCG'],
'H':['CAU','CAC'],
'Q':['CAA','CAG'],
'R':['CGU','CGC','CGA','CGG','AGA','AGG'],
'I':['AUU','AUC','AUA'],
'M':['AUG'],
'T':['ACU','ACC','ACA','ACG'],
'N':['AAU','AAC'],
'K':['AAA','AAG'],
'V':['GUU','GUC','GUA','GUG'],
'A':['GCU','GCC','GCA','GCG'],
'D':['GAU','GAC'],
'E':['GAA','GAG'],
'G':['GGU','GGC','GGA','GGG']
}

string = 'MKDGVHLHFYIVMRWMQFDTPHEKYAKPHSCGAVMCTLLNHDWTHGHAEYWDNVFQPPREPIFWYYYVEIKTLYTPGIEQWYLEQGYNITSMCRCRFMTHTCREVMRVDLPMWSFPAHWAKTKCATQVTQNEWFPMLRYNSIYSIPNRSNGTQDHHELFIEVCSMWCDSCTFEWHYDNEKQIEAWFNWRWSEYVIMMRWMIDRSHKAPEEWYFQMFAGDDQAYHMGKACAMTCHKQHLECWILWIQNVYKVEKSHDRVPLQERRFMVRNFERKEGGTNPHAETAYCITNFGCSMTFAYESHWAEQMDNPARPWHIETGAVRPYPLFICQQFVLCRVWWWKVTNINDKHQQMHHKHIDWQMCSNKWGPDTSHNASTTEGVFWEMLYLWMSNPQWPMEWIVYREKCFWYYVVGPEDCAIPEHMAGNQITMSYHWPNSHIEEFIIYEGWMLKESLACLQKALTKGDGHQHVMDCSTKSFEALTPSAFMASRYPLIQFFTRWHGNIIWRSMFILWMDRWLYKHVCLRCPHIAWKCDKVNFPDKCAQDGDCLRGDKMWAYYTGAHVRSPYTCKQGFKCTPRDNQWCGCQDPSHISENQCLVWCTREYMFCIVNSIRGCYECWIWPWALVWLQETIRSDMTPLGSDWDEKHHMRHVIIKSAWRYYDYTECKKCVKSADYPAFHNNDKEYWATFFAWFCMMGSQDGFCPFWFKSFRPFPYWYGQMIKFLIHQGDQSVMYCGWKNLYWENQNGQSHYVCRDQRGSMEDHQMENDSIPFMLERLAEISLTKTVNPERNGGAKFLRCQDVYVNRTMNLDSDNSGFPEQSRRLTLAPRYPAQYYVTIWVVQQICSHSAYQEHLWRVGATKSVERACHHAITITRFAWRGAADYASDGFECMNQEELFQGGSELCDCSIGRPWQTMALYGWDDFGHCPFYLFGRNLQNVKIMYIDHWMFEIYGFWAMVWLFVPTLHLMGKQENDPPHGGDFVPCCIQKWSRAHYGFVNQTNV'
string = list(string)
string.append('Stop')
RNA = 1
for p in string:
	RNA *= len(aa[p])

print(RNA%1000000)